version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.production
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    working_dir: /usr/src/app/
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
     - 8000
    #ports:
    #  - 8000:8000
    env_file:
      - ./.env.production
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./var/db/data:/var/lib/postgresql/data/
    env_file:
      - ./.env.production
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    #expose:
    # - 80
    ports:
      - "80:80"
    volumes:
      - media_volume:/usr/src/app/mediafiles
    depends_on:
      - app
    links:
      - app

volumes:
  static_volume:
  media_volume:
