version: "3.7"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nginx
    #links:
    #  - nginx
    # Restart https-portal on failure or after Docker host restart.
    restart: always
    environment:
      DOMAINS: 'owaranai.omata.org -> http://nginx:80'
      STAGE: 'production'
      #STAGE: 'local'
    volumes:
      - ./var/lib/ssl_certs:/var/lib/https-portal
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.production
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    working_dir: /usr/src/app/
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.production
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.production
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.production
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  db_data:
  static_volume:
  media_volume:
